fitur_profile/urls.py
from django.conf.urls import url
from .views import *
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^profile/edit/$', editProfile, name='edit'),
    url(r'^profile/save/$', change_user_data, name='save'),
    url(r'^get_data/$', get_allSkill, name="skill"),
]

fitur_riwayat/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^riwayat/$', index, name='riwayat'),
]

tugas2ppw/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static

import fitur_loginStatus.urls as loginStatus
import fitur_profile.urls as profile
import fitur_riwayat.urls as riwayat
import fitur_cariMahasiswa.urls as cariMahasiswa


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^fitur-login-status/', include(loginStatus,namespace='fitur_loginStatus')),
    url(r'^fitur-profile/', include(profile,namespace='fitur-profile')),
    url(r'^fitur-riwayat/', include(riwayat,namespace='fitur-riwayat')),
    url(r'^fitur-cariMahasiswa/', include(cariMahasiswa,namespace='fitur-cariMahasiswa')),
	url(r'^$', RedirectView.as_view(url="fitur-login-status/", permanent="true"), name='index'),
]

fitur_profile/models.py
from django.db import models

# Create your models here.


class User(models.Model):
    name = models.CharField(max_length=200, default="-", null=True)
    npm = models.CharField(max_length=200, default="-", null=True)
    skill = models.CharField(max_length=200, default="-", null=True)
    email = models.CharField(max_length=200, default="-", null=True)
    linkProfile = models.CharField(max_length=200, default="-", null=True)
    imgUrl = models.CharField(max_length=400, default="-", null=True)

fitur_profile/views.py
from django.shortcuts import render
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.urls import reverse
from .models import User
from django.views.decorators.csrf import csrf_exempt
import json
from fitur_loginStatus.models import *
from fitur_loginStatus.forms import *

# Create your views here.
response = {}
def index(request):

    ## sol : bagaimana cara mencegah error, jika url profile langsung diakses
    if 'user_login' not in request.session.keys():
        return HttpResponseRedirect(reverse('fitur_loginStatus:index'))
    ## end of sol
    set_data_for_session(response, request)

    sudahAda = User.objects.filter(npm=response['kode_identitas'])
    if not sudahAda :
        newUser = User.objects.create(npm=response['kode_identitas'])
        newUser.save()
        print("User Baru"+str(newUser.npm))

    pengguna = User.objects.get(npm=response['kode_identitas'])
    response['id'] = pengguna.id

    get_data_user(pengguna)

    postt = Post.objects.order_by('-created_date')

    count = 0;
    count = Post.objects.all().count()
    response['total'] = count
    print("dasdadadasda")

    response['post'] = postt

    status = "kosong"
    status = Post.objects.all()[count-1].content
    response['statusku'] = status
    print("abc")

    html = 'fitur_profile/profilePage.html'
    return render(request, html, response)

def set_data_for_session(res, request):
    response['author'] = request.session['user_login']
    response['access_token'] = request.session['access_token']
    response['kode_identitas'] = request.session['kode_identitas']
    response['role'] = request.session['role']

def editProfile(request):
    html = 'fitur_profile/editProfile.html'
    return render(request, html, response)

def get_data_user(pengguna):
    response['user'] = pengguna
    response['keahlian'] = pengguna.skill.split(" ")

@csrf_exempt
def change_user_data(request):
    if request.method == 'POST':
        pengguna = User.objects.get(npm=request.session['kode_identitas'])
        pengguna.name = request.POST.get('name')
        pengguna.skill = request.POST.get('skills')
        pengguna.email = request.POST.get('email')
        pengguna.linkProfile = request.POST.get('linkin')
        pengguna.imgUrl = request.POST.get('url')
        pengguna.save()
        print(pengguna.name)
    return HttpResponseRedirect(reverse('fitur-profile:index'))

def get_allSkill(request):
    pengguna = User.objects.get(npm=request.session['kode_identitas'])
    lst = pengguna.skill.strip().split(" ")
    return JsonResponse({'ahli':lst})

fitur_profile/templates/fitur_profile/layout/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="{% static 'css/profile.css' %}" rel="stylesheet">
	<link href="{% static 'css/fitur_cariMahasiswa.css' %}" rel="stylesheet">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <title>
    </title>
	<style>
		.navbar-default{
			background-color: black;
			margin-bottom: 0;
		}
		.container2{
			text-align: center;
		}

    .rata-tengah {
      text-align: center;
      margin : 20px;
    }
    .judul {
      text-transform:uppercase;
      margin-bottom: 50px;
      margin-top: 50px;
    }
	</style>
</head>
<body>
<header>
	{% include "fitur_profile/partials/header.html" %}
</header>
<content>
    <div class="container-fluid" id="mainContainer">
        {% block contents %}
        <!-- Your Content Here -->
        {% endblock %}
    </div>
</content>
    <footer>
  		<div style="text-align:center">
          {% block footer %}
          {% include "fitur_profile/partials/footer.html" %}
          {% endblock %}
  		</div>
    </footer>

<!-- Jquery n Bootstrap Script -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/css/select2.min.css" rel="stylesheet" />
<script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/js/select2.min.js"></script>
<script src="{% static 'js/profile.js' %}"></script>
<script src="{% static 'js/fitur_cariMahasiswa.js' %}"></script>
<script src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
<script>
 var url1 = "{% url 'fitur-riwayat:riwayat' %}";
</script>
{% block javascript %}

{% endblock %}
</body>
</html>